openapi: 3.0.1
info:
  title: '@jupiterone/graph-vsphere'
  description: A JupiterOne Integration for ingesting data of the VMware vSphere
  x-cortex-git:
    github:
      repository: JupiterOne/graph-vsphere
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-vsphere'
  x-cortex-service-groups:
    - tier-4
